# Opacity
inactive-opacity = 0.8;
frame-opacity = 1.0;
inactive-opacity-override = false;


opacity-rule = [
	"90:class_g  = 'kitty' && focused",
	"70:class_g  = 'kitty' && !focused",
	"100:class_g = 'firefox'",
	"100:class_g = 'Steam'",
];

# Blur
blur: {
	method = "kawase";
	strength = 2;
	background = false;
	background-frame = false;
	background-fixed = false;
	background-exclude = [
		"window_type = 'dock'",
		"window_type = 'desktop'",
		"_GTK_FRAME_EXTENTS@:c",
	];
}
backend = "glx";
glx-no-stencil = true;
vsync = true;
